### ISSUE TITLE
key-file support.

### ISSUE THREAD

**Issue by rodin-ia** [shikaan/keydex#16]
Hi, it would be cool to add support for databases that use key-file in addition to password.
Thanks for the program.

**Comment by shikaan** [comment]
Hey, thanks for opening the issue!

I will try taking a look tomorrow and come back with an ETA for you

**Comment by shikaan** [comment]
Hey @rodin-ia

It's been a while I have been working on this project, and I forgot that in fact that is already supported :sweat_smile: 

You should be able to do so using
```shell
keydex open database.kdbx -k key.key
```

Was there a specific problem you are facing that you cannot solve?

**Comment by rodin-ia** [comment]
Shit, right. I hadn't noticed. Thank you!
