### ISSUE TITLE
[bug] Hangs when trying to reveal long field

### ISSUE THREAD

**Issue by Xotchkass** [shikaan/keydex#19]
The app hung (became unresponsive) when I tried to reveal the github recovery code field. It also had pretty high CPU utilization, so is there probably a busyloop somewhere. 
Maybe because of newlines in the string it can't render it properly or doesn't handle out of bounds index somewhere.

**Comment by shikaan** [comment]
Hey, I somehow missed the notification. Thanks for the report!

Can you give me an (obfuscated) example string that hangs? I am not sure what you mean by Github recovery code in this context.

**Comment by Xotchkass** [comment]
It's 16 lines (like I said, my guess it that it doesn't handle newlines properly) 11 ASCII chars each.
Looks like this:

```
762ae-d2193
f3725-16db6
eed4f-316ec
2730b-c3de5
69445-508b1
f3731-95bf5
bb3ef-de5fc
82518-e6479
a4561-3be54
ffa0e-dba10
7ee65-c940f
88110-40c70
c4f52-f661a
bf6b4-164b5
716e9-507fa
035e3-28180
```
(It's not mine. Just randomly generated. Also you might want to grab your own. It's in Settings>Password and authentication>Two-factor authentication>Recovery codes)

**Comment by shikaan** [comment]
Thanks :) I'll try giving this a shot during the Christmas break and get back to you. Thanks for your help!

**Comment by shikaan** [comment]
Code is still a little bit messy, but #20 should do the trick.

Wanna give it a shot with a debug build? 
https://github.com/shikaan/keydex/releases/tag/v0.4.0

Thanks!

**Comment by Xotchkass** [comment]
The [build](https://github.com/shikaan/keydex/releases/tag/v0.7.0) crashes immediately after opening database 
```
panic: runtime error: index out of range [0] with length 0

goroutine 7 [running]:
github.com/shikaan/keydex/tui/components.(*Input).HandleEvent.func1()
        /source/tui/components/input.go:266 +0xd7
github.com/shikaan/keydex/tui/components.(*Input).handleCellsUpdate(0xc000022410, {0xd276e0, 0xc000296de0}, 0x1?)
        /source/tui/components/input.go:302 +0x29
github.com/shikaan/keydex/tui/components.(*Input).HandleEvent(0xc000022410, {0xd276e0?, 0xc000296de0?})
        /source/tui/components/input.go:261 +0x1d2
github.com/gdamore/tcell/v2/views.(*BoxLayout).HandleEvent(0x1?, {0xd276e0, 0xc000296de0})
        /go/pkg/mod/github.com/gdamore/tcell/v2@v2.7.4/views/boxlayout.go:240 +0xbe
github.com/gdamore/tcell/v2/views.(*BoxLayout).HandleEvent(0x730001e280?, {0xd276e0, 0xc000296de0})
        /go/pkg/mod/github.com/gdamore/tcell/v2@v2.7.4/views/boxlayout.go:240 +0xbe
github.com/gdamore/tcell/v2/views.(*BoxLayout).HandleEvent(0xc000296de0?, {0xd276e0, 0xc000296de0})
        /go/pkg/mod/github.com/gdamore/tcell/v2@v2.7.4/views/boxlayout.go:240 +0xbe
github.com/shikaan/keydex/tui.(*Layout).HandleEvent(0xc000096b00?, {0xd276e0?, 0xc000296de0?})
        /source/tui/layout.go:52 +0x1e8
github.com/gdamore/tcell/v2/views.(*Application).run(0xf87810)
        /go/pkg/mod/github.com/gdamore/tcell/v2@v2.7.4/views/app.go:163 +0x388
created by github.com/gdamore/tcell/v2/views.(*Application).Start in goroutine 1
        /go/pkg/mod/github.com/gdamore/tcell/v2@v2.7.4/views/app.go:173 +0x65
```

Tried to build the [fix branch](https://github.com/shikaan/keydex/tree/fix/19--hang-on-line-breaks) but couldn't
``` shell
$ make build
> (build) Running the build...
pkg\errors\errors.go:6:2: no required module provides package github.com/shikaan/keydex/pkg/info; to add it:
        go get github.com/shikaan/keydex/pkg/info
make: *** [Makefile:6: build] Error 1

$  go get github.com/shikaan/keydex/pkg/info
go: github.com/shikaan/keydex/pkg/info: no matching versions for query "upgrade"
```

**Comment by shikaan** [comment]
I didn't ask because I assumed the problem was platform independent by the looks of it, but maybe it isn't 🤔 Any chance you can share your specs?

--- 

I realised that build is some messed up in between state, because I never cared too much about polishing the prerelease flow 😅 I'll get you a usable one soon

---

To build, you need to `make info` first, as per the contribution guidelines. I should probably just make that a recipe dependency, I reckon, or at least make it spit a useful error. Thanks for the help there too

**Comment by shikaan** [comment]
https://github.com/shikaan/keydex/releases/tag/v0.4.0-alpha.1

This should be working, to see at least if the initial bug is solved for you. I will need to test it a little more thoroughly since I ended up refactoring a bunch of things

**Comment by Xotchkass** [comment]
> share your specs

Win10, x86_64

> as per the contribution guidelines

Yeah, I probably should've read those. Sorry.😅

> https://github.com/shikaan/keydex/releases/tag/v0.4.0-alpha.1

Yep, works fine. Thanks for the fix.
![изображение](https://github.com/user-attachments/assets/89329ad9-a190-40f4-99ac-e3c75506eaf4)

Also, on a side note, another nice improvement would be to remove the newlines when the field is hidden. 
![изображение](https://github.com/user-attachments/assets/0acbda41-d1d5-4b2e-8efc-9f4694a3d1a3)

**Comment by shikaan** [comment]
No problem! Thank you for the report :) I'll keep you posted once we have a stable version out

**Comment by shikaan** [comment]
New stable is out :) Thanks for your help one more time!
